#!/usr/bin/env python3
"""Maintain paired UI translations and emit the Xcode string catalog."""
import json
from pathlib import Path
rows = {
 'value.yes': ('Yes', '是'), 'value.no': ('No', '否'),
'diagnostics.os': ('macOS: %@', 'macOS：%@'), 'diagnostics.runtime': ('Codex Desktop: %@', 'Codex Desktop：%@'), 'diagnostics.path': ('App path: %@', '应用路径：%@'), 'diagnostics.executable': ('Executable found: %@', '找到可执行文件：%@'), 'diagnostics.permission': ('Accessibility: %@', '辅助功能权限：%@'), 'diagnostics.storage': ('Metadata storage writable: %@', '元数据可写：%@'), 'diagnostics.profiles': ('Profiles:', '配置：'), 'diagnostics.external': ('External / unknown instances: %d', '外部或未知实例：%d'), 'diagnostics.auth': ('Authentication is inferred from file metadata only. Credentials and window titles are omitted.', '仅通过文件元数据推测认证状态。已排除凭据和窗口标题。'),
'file.title': ('File', '文件'), 'action.close': ('Close Window', '关闭窗口'),
'app.quit': ('Quit CodexM', '退出 CodexM'),
'app.loading': ('Loading profiles…', '正在载入配置…'),
'app.independent': ('CodexM is an independent project and is not affiliated with or endorsed by OpenAI.', 'CodexM 是独立项目，与 OpenAI 无关联，亦未经其背书。'),
'edit.title': ('Edit', '编辑'), 'edit.undo': ('Undo', '撤销'), 'edit.cut': ('Cut', '剪切'), 'edit.copy': ('Copy', '复制'), 'edit.paste': ('Paste', '粘贴'), 'edit.selectAll': ('Select All', '全选'),
'action.focus': ('Focus', '切换到窗口'), 'action.newWindow': ('New Window', '新建窗口'), 'action.restart': ('Restart', '重新启动'), 'action.stop': ('Quit Profile', '退出此配置'), 'action.forceQuit': ('Force Quit', '强制退出'), 'action.launch': ('Launch', '启动'), 'action.edit': ('Edit…', '编辑…'), 'action.delete': ('Delete', '删除'), 'action.more': ('More actions', '更多操作'), 'action.ok': ('OK', '好'), 'action.cancel': ('Cancel', '取消'), 'action.save': ('Save', '保存'), 'action.done': ('Done', '完成'), 'action.back': ('Back', '上一步'), 'action.continue': ('Continue', '继续'), 'action.retry': ('Retry', '重试'), 'action.dismiss': ('Dismiss', '知道了'), 'action.settings': ('Settings', '设置'), 'action.windows': ('Show Windows', '查看窗口'),
'state.stopped': ('Stopped', '未运行'), 'state.launching': ('Launching', '正在启动'), 'state.running': ('Running', '运行中'), 'state.terminating': ('Quitting', '正在退出'), 'state.crashed': ('Crashed', '异常退出'), 'state.error': ('Error', '出错'),
'profile.add': ('Add Profile', '添加配置'), 'profile.edit': ('Edit Profile', '编辑配置'), 'profile.name': ('Profile name', '配置名称'), 'profile.nameHint': ('1–64 characters. Chinese and other Unicode names are welcome.', '1–64 个字符，支持中文及其他 Unicode 名称。'), 'profile.autoLaunch': ('Launch this profile when CodexM starts', 'CodexM 启动时自动启动此配置'), 'profile.restore': ('Include this profile when restoring a previous session', '恢复上次运行状态时包含此配置'), 'profile.restoreHint': ('Session restoration must also be enabled in Settings.', '还需在设置中开启恢复上次运行配置。'), 'profile.empty': ('A place for every Codex identity', '为每个 Codex 身份留一个位置'), 'profile.emptyDescription': ('Create a profile to keep its app data and sign-in separate.', '创建配置，让应用数据与登录状态独立保存。'), 'profile.ready': ('Ready when you are.', '随时可以启动。'), 'profile.inUse': ('This data directory is in use by an unrecognized instance.', '此数据目录正被未识别的实例使用。'),
'dashboard.title': ('Your profiles', '我的配置'), 'dashboard.summary': ('Profiles: %d · Running: %d', '%d 个配置 · %d 个运行中'), 'dashboard.local': ('Local data. Official Codex.', '数据在本机，运行官方 Codex。'),
'menu.running': ('%d running', '%d 个运行中'), 'menu.open': ('Manage Accounts', '管理账户'),
'window.count': ('Windows: %d', '%d 个窗口'), 'window.untitled': ('Codex window', 'Codex 窗口'), 'window.empty': ('No accessible windows yet. Open a window in Codex and try again.', '暂未发现可管理的窗口。请在 Codex 中打开窗口后重试。'), 'window.permissionRequired': ('Window controls need Accessibility', '窗口操作需要辅助功能权限'),
'auth.unknown': ('Sign-in status unknown', '登录状态未知'), 'auth.signedOut': ('No local sign-in file detected', '未检测到本地登录文件'), 'auth.signingIn': ('Watching for sign-in activity…', '正在观察登录活动…'), 'auth.signedIn': ('Sign-in file present · status unverified', '存在登录文件 · 状态未经验证'), 'auth.return': ('Return to this sign-in window', '返回此配置的登录窗口'),
'runtime.missing': ('Codex Desktop was not found.', '未找到 Codex Desktop。'), 'runtime.locate': ('Locate App…', '选择应用…'), 'runtime.detect': ('Detect Again', '重新检测'), 'runtime.version': ('Version', '版本'), 'runtime.path': ('App path', '应用路径'), 'runtime.updated': ('Codex Desktop was updated. Some CodexM features may need compatibility verification.', '检测到 Codex Desktop 已更新，部分 CodexM 功能可能需要重新验证兼容性。'),
'external.title': ('External Codex', '外部 Codex'), 'external.description': ('These instances were not reliably linked to a managed profile. CodexM leaves them alone.', '这些实例无法可靠关联到已管理配置。CodexM 不会接管或退出它们。'), 'external.pid': ('Process %d · unmanaged', '进程 %d · 未接管'),
'settings.title': ('General Settings', '通用设置'), 'settings.general': ('General', '通用'), 'settings.login': ('Launch CodexM at login', '登录 Mac 时启动 CodexM'), 'settings.loginApproval': ('Approve in Login Items…', '前往登录项批准…'), 'settings.restore': ('Restore previously running profiles when CodexM starts', 'CodexM 启动时恢复上次运行的配置'), 'settings.language': ('Language', '语言'), 'language.system': ('Follow System', '跟随系统'), 'language.en': ('English', 'English'), 'language.zhHans': ('简体中文', '简体中文'), 'settings.runtime': ('Codex Desktop', 'Codex Desktop'), 'settings.behavior': ('Behavior', '行为'), 'settings.click': ('Click a running profile', '点击运行中的配置'), 'settings.lastWindow': ('Focus Last Window', '聚焦上次使用的窗口'), 'settings.showWindows': ('Show Windows', '显示窗口列表'), 'settings.quitInstances': ('Quit managed Codex instances when quitting CodexM', '退出 CodexM 时一并退出已管理的 Codex 实例'), 'settings.quitHint': ('Off by default. Codex keeps running after CodexM closes.', '默认关闭。关闭 CodexM 后，Codex 将继续运行。'), 'settings.advanced': ('Advanced', '高级'), 'settings.dataFolder': ('Open CodexM Data Folder', '打开 CodexM 数据目录'),
'accessibility.compact': ('Enable Accessibility for window controls.', '开启辅助功能以管理窗口。'),
'accessibility.title': ('Accessibility', '辅助功能'), 'accessibility.explanation': ('CodexM needs Accessibility permission to focus and manage Codex windows.', 'CodexM 需要“辅助功能”权限，以聚焦和管理 Codex 窗口。'), 'accessibility.granted': ('Accessibility is enabled', '已开启辅助功能权限'), 'accessibility.missing': ('Accessibility is not enabled', '尚未开启辅助功能权限'), 'accessibility.optional': ('You can create, launch and quit profiles without this permission.', '未授权也能创建、启动和退出配置。'), 'accessibility.request': ('Request Permission', '请求权限'), 'accessibility.openSettings': ('Open System Settings', '打开系统设置'),
'diagnostics.title': ('Diagnostics', '诊断'), 'diagnostics.privacy': ('Includes profile names, IDs and app paths. Review before sharing. Credentials and window titles are never included.', '包含配置名称、标识和应用路径，请检查后再分享。不包含凭据或窗口标题。'), 'diagnostics.copy': ('Copy Diagnostics', '复制诊断信息'), 'diagnostics.copied': ('Copied', '已复制'),
'delete.title': ('Delete this profile?', '删除此配置？'), 'delete.confirm': ('Move Profile to Trash', '将配置移到废纸篓'), 'delete.message': ('“%@” and its local app data will be moved to the Trash. This does not delete an OpenAI account.', '“%@”及其本机应用数据将移到废纸篓。这不会删除 OpenAI 账号。'), 'force.title': ('The profile has not quit', '此配置尚未退出'), 'force.message': ('Normal quit timed out. You can wait, or explicitly force quit this profile. Unsaved work may be lost.', '正常退出已超时。你可以继续等待，或明确选择强制退出此配置。未保存的工作可能丢失。'),
'storage.failed': ('Profile metadata could not be opened safely. No existing data was overwritten. Check Diagnostics and the data folder, then reopen CodexM.', '无法安全打开配置元数据。现有数据未被覆盖。请检查诊断和数据目录后重新打开 CodexM。'), 'storage.writeFailed': ('Changes could not be saved. Check free disk space and folder permissions, then retry.', '无法保存更改。请检查磁盘空间和目录权限后重试。'),
'onboarding.step': ('Step %d of %d', '第 %d 步，共 %d 步'), 'onboarding.title.0': ('Welcome to CodexM', '欢迎使用 CodexM'), 'onboarding.title.1': ('Find your Codex app', '找到你的 Codex 应用'), 'onboarding.title.2': ('Switch windows with ease', '轻松切换窗口'), 'onboarding.title.3': ('Create your first profile', '创建第一个配置'), 'onboarding.body.0': ('Keep personal, work and testing identities in their own local profiles. Each profile runs the official Codex app.', '将个人、工作和测试身份分别保存在本机配置中。每个配置都运行官方 Codex 应用。'), 'onboarding.body.1': ('CodexM uses the official app already installed on your Mac. You can choose a different location if needed.', 'CodexM 使用 Mac 上已安装的官方应用。需要时也可以手动选择应用位置。'), 'onboarding.body.2': ('Accessibility lets CodexM list and focus the correct windows. You can enable it now or later in Settings.', '辅助功能权限让 CodexM 列出并聚焦正确的窗口。你可以现在开启，或稍后在设置中开启。'), 'onboarding.body.3': ('Choose a name you recognize. Start the profile whenever you are ready, then sign in inside the official Codex app.', '选择一个容易辨认的名称。准备好后启动此配置，并在官方 Codex 应用中登录。'), 'onboarding.feature1': ('Independent local profiles', '相互独立的本机配置'), 'onboarding.feature2': ('One menu bar, all your instances', '一个菜单栏，管理所有实例'), 'onboarding.feature3': ('No credential copying or account proxy', '不复制凭据，不代理账号请求'), 'onboarding.later': ('Set Up Later', '稍后设置'), 'onboarding.create': ('Create Profile', '创建配置'),
'error.title': ('Could not complete the action', '无法完成操作'),
'error.invalidName': ('Enter a name of 1–64 characters, without line breaks or control characters.', '请输入 1–64 个字符的名称，不含换行或控制字符。'),
'error.codexNotFound': ('Locate the official Codex Desktop app in Settings before launching a profile.', '请先在设置中选择官方 Codex Desktop 应用，再启动配置。'),
'error.incompatibleRuntime': ('This is not a valid Codex Desktop app (com.openai.codex), or its executable is unavailable.', '此应用不是有效的 Codex Desktop（com.openai.codex），或其可执行文件不可用。'),
'error.profileNotFound': ('This profile no longer exists.', '此配置已不存在。'),
'error.profileAlreadyRunning': ('This profile already has an active instance.', '此配置已有运行中的实例。'),
'error.launchFailed': ('Codex could not be started. Check the selected app and directory permissions, then try again.', '无法启动 Codex。请检查所选应用和目录权限后重试。'),
'error.accessibilityDenied': ('macOS has not granted Accessibility permission to this copy of CodexM. Creating and selecting windows requires this permission. Enable it for the currently running app in System Settings > Privacy & Security > Accessibility.', 'macOS 尚未授予当前这份 CodexM 辅助功能权限，无法执行新建或精确选择窗口。请在系统设置 → 隐私与安全性 → 辅助功能中授权当前运行的应用；若旧版本已授权，请移除旧条目后重新添加。'),
'window.note': ('Window note (optional)', '窗口备注（可选）'),
'window.noteHint': ('Some official windows always report ChatGPT. Add a note to distinguish them in CodexM. Notes last until this window closes; clear a note to use the live title.', '部分官方窗口始终返回 ChatGPT。可添加备注，在 CodexM 中区分窗口。备注仅保留至此窗口关闭；清空后恢复实时标题。'),
'window.permissionHint': ('Window details require Accessibility permission', '读取窗口详情需要辅助功能权限'),
'error.windowNotFound': ('The window is no longer accessible. Try opening a window in this Codex instance.', '此窗口已无法访问。请尝试在此 Codex 实例中打开窗口。'),
'error.newWindowUnavailable': ('The official New Window menu command is unavailable or not recognized. Use File → New Window in this Codex instance. No extra instance was launched.', '官方新建窗口菜单当前不可用或无法识别。请在此 Codex 实例中使用“文件 → 新建窗口”。未启动额外实例。'),
'error.filesystemError': ('The local data operation failed. Check folder permissions and free disk space.', '本机数据操作失败。请检查目录权限和磁盘空间。'),
'error.corruptStorage': ('The metadata file is unreadable or has an unsupported format. It has not been overwritten. Restore a valid metadata backup and reopen CodexM.', '元数据文件无法读取或格式不受支持。文件未被覆盖。请恢复有效的元数据备份后重新打开 CodexM。'),
'error.unsafePath': ('A profile path contains an unexpected symbolic link or invalid directory. No data was changed.', '配置路径含有非预期的符号链接或无效目录。未更改数据。'),
'error.profileBusy': ('This profile is running, locked, or being changed. Wait for it to stop before trying again.', '此配置正在运行、被锁定或正在更改。请等待停止后重试。'),
'error.processChanged': ('The original process is no longer running. Refresh and try again.', '原进程已不再运行。请刷新后重试。'),
'error.terminationFailed': ('Codex did not accept the quit request. Check the instance for a confirmation dialog and try again.', 'Codex 未接受退出请求。请检查实例中是否有确认对话框后重试。'),
'error.storageLocked': ('Another CodexM process is using this data folder, or the folder cannot be locked. Use the existing CodexM or check folder permissions.', '另一个 CodexM 进程正在使用此数据目录，或目录无法锁定。请使用已有 CodexM，或检查目录权限。'),
'error.ambiguousInstance': ('An unrecognized process is already using this profile directory. Quit it yourself before launching or deleting the profile.', '一个未识别的进程正在使用此配置目录。请自行退出该进程后再启动或删除此配置。'),
'error.unavailable': ('The operation is unavailable. Check the app state and try again.', '当前无法执行此操作。请检查应用状态后重试。'),
'error.loginItemFailed': ('The login item could not be changed. Keep CodexM in Applications and check System Settings → General → Login Items.', '无法更改登录项。请将 CodexM 放在“应用程序”目录，并检查“系统设置 → 通用 → 登录项”。'),
}
rows = {k: (en.replace('Profiles', 'Accounts').replace('profiles', 'accounts').replace('Profile', 'Account').replace('profile', 'account').replace('Codex Desktop', 'ChatGPT'), zh.replace('配置', '账户').replace('Codex Desktop', 'ChatGPT')) for k, (en, zh) in rows.items() if not k.startswith(('onboarding.', 'diagnostics.')) and k not in ['settings.advanced', 'settings.dataFolder']}
rows.update({
'account.default': ('Default account', '默认账户'),
'account.local': ('Default', '默认'),
'account.defaultHint': ('Uses the installed app’s original data. CodexM never deletes or relocates it.', '使用已安装应用的原始数据，CodexM 不会删除或迁移此账户。'),
'error.defaultAccountProtected': ('The original default account cannot be deleted or stopped by CodexM.', 'CodexM 不会删除或停止本机默认账户。'),
'error.directoryNotEmpty': ('The destination already contains an account folder with the same ID. Choose another directory.', '目标位置已存在相同 ID 的账户目录，请选择其他目录。'),
'settings.runtime': ('Installed ChatGPT', '已安装的 ChatGPT'),
'runtime.dropHint': ('Drop the installed ChatGPT app here to read its path, or select it below.', '将已安装的 ChatGPT 应用拖到此设置窗口读取路径，也可以点击下方按钮选择。'),
'settings.restoreExample': ('For example: if Personal and Work were running when CodexM quit, reopen CodexM to start them again. Stopped accounts remain stopped. Requires restoration enabled for each account.', '例如：退出 CodexM 时“个人”和“工作”正在运行，下次打开时会恢复这两个账户，原本停止的账户不会启动。账户本身也需开启允许恢复。'),
'settings.accountDirectory': ('Account data directory', '账户数据目录'),
'settings.chooseDirectory': ('Choose directory…', '设置目录…'),
'settings.directoryHint': ('Stop added accounts before changing this directory. Existing data is copied to the new location; old folders are kept as backups. The installed default account stays in its original location.', '更改前请先停止新增账户。已有数据将复制到新目录，原目录保留为备份；本机默认账户仍使用原位置。'),
})
rows.update({
'handoff.title': ('Project Handoff', '项目接力'),
'handoff.from': ('From account', '来源账户'),
'handoff.to': ('To account', '目标账户'),
'handoff.chooseTarget': ('Choose an account', '请选择账户'),
'handoff.search': ('Search task title or project path', '搜索任务名称或项目路径'),
'handoff.tasks': ('Recent tasks · latest 500', '最近任务 · 最近 500 条'),
'handoff.archived': ('Archived', '已归档'),
'handoff.empty': ('No matching tasks', '没有匹配的任务'),
'handoff.localHint': ('Context handoff creates a new task with the original request and recent excerpts. It does not transfer the full native history or account credentials.', '上下文接力：在目标账户新建任务，保留原始请求和近期摘录；不会迁移原任务的完整历史或账户凭据。'),
'handoff.recent': ('Recent handoffs', '最近接力记录'),
'handoff.status.ready': ('Ready', '已准备'),
'handoff.status.launched': ('Target opened', '已打开目标账户'),
'handoff.status.failed': ('Open failed · package retained', '打开失败 · 接力包已保留'),
'handoff.back': ('Back', '返回'),
'handoff.preview': ('Preview', '预览接力'),
'handoff.execute': ('Handoff & Copy Instructions', '接力并复制继续指令'),
'handoff.events': ('%d events · %d sensitive matches redacted', '%d 条事件 · 已脱敏 %d 处疑似敏感内容'),
'handoff.noGit': ('Git state unavailable', '无法获取 Git 状态'),
'handoff.limited': ('Context was shortened. Review and edit before continuing. Basic redaction cannot detect every secret.', '上下文已截取压缩，请检查并补充后继续。基础脱敏无法识别所有敏感信息。'),
'handoff.reviewHint': ('Review and edit these excerpts before continuing. Basic redaction cannot detect every secret.', '请检查并补充以下摘录后继续。基础脱敏无法识别所有敏感信息。'),
'handoff.context': ('Handoff context', '接力上下文'),
'handoff.pauseHint': ('Pause source work before continuing: both accounts use the same project files. The next step copies instructions and opens the target account; no prompt is submitted automatically.', '继续前请暂停来源任务，两边使用同一份项目文件。下一步会复制继续指令并打开目标账户，不会自动发送任务。'),
'handoff.ready': ('Handoff package ready', '接力包已准备好'),
'handoff.targetName': ('Target account: %@', '目标账户：%@'),
'handoff.missingAccount': ('Account removed', '账户已移除'),
'handoff.manual': ('In the target account, open the project shown above, create a new task, then paste and send the copied instructions. This version does not automatically create or submit a task. You can reopen this package later.', '在目标账户中打开上方项目目录，新建任务，粘贴并发送已复制的继续指令。本版不自动创建或发送任务，接力包可随时重新打开。'),
'handoff.copy': ('Copy Instructions', '复制继续指令'),
'handoff.copied': ('Copied', '已复制'),
'handoff.reveal': ('Show Context File', '显示上下文文件'),
'handoff.openTarget': ('Copy & Open Target', '复制并打开目标账户'),
'handoff.previewMode': ('Preview mode does not open real accounts. The package is ready.', '预览模式不会打开真实账户，接力包已准备好。'),
'handoff.launchFailed': ('Could not open the target account. The package is saved; resolve the launch issue and try again.', '未能打开目标账户，接力包已保存。解决启动问题后可重试。'),
'error.handoffNoDatabase': ('No local task database for this account yet. Open the account and create a task first.', '此账户尚无本地任务数据库，请先打开该账户并创建任务。'),
'error.handoffDatabase': ('Could not read the task list. It may be busy or inaccessible; try again shortly. Account launching is unaffected.', '暂时无法读取任务列表，可能被占用或没有访问权限。请稍后重试，账户启动不受影响。'),
'error.handoffSchema': ('Context Handoff is unavailable for this task database version. Account launching is unaffected.', '此任务数据库版本暂不支持上下文接力，账户启动不受影响。'),
'error.handoffTranscript': ('No readable supported conversation events were found. The source file may be missing or its format may have changed.', '没有可读取的受支持对话事件，源会话文件可能缺失或格式已变化。'),
'error.handoffSelection': ('Choose a task from the source account and a different target account.', '请选择来源账户中的任务，并选择另一个目标账户。'),
'error.handoffPackage': ('Could not read or save the handoff package. Check directory permissions and free space.', '无法读取或保存接力包，请检查目录权限和磁盘空间。'),
'error.handoffProject': ('The project directory no longer exists. The package is retained; locate the project before continuing.', '原项目目录已不存在，接力包仍然保留。请找到项目目录后再继续。'),
})
rows.update({
'accessibility.refresh': ('Check Permission', '重新检测'),
'settings.permissionApp': ('Current CodexM app', '当前 CodexM 应用'),
'accessibility.reauthorizeHint': ('If permission is enabled but not detected after an update, remove the old CodexM entry in Accessibility and add this app again. Local unsigned-release identity can change between builds. Reopen CodexM if macOS requests it.', '若更新后系统中已开启权限，但此处仍未识别，请在辅助功能列表中移除旧 CodexM，再添加上方路径的应用。当前本地签名版本在更新后可能需要重新授权；若系统要求，请重新打开 CodexM。'),
})
rows.update({
'action.edit': ('Rename', '重命名'), 'profile.edit': ('Rename Account', '重命名账户'),
'action.more': ('More actions', '更多操作'),
'window.distinguished': ('%@ · Window %d', '%@ · 窗口 %d'),
'app.version': ('Version', '版本号'),
'app.repository': ('github.com/5hux1n/codexm', 'github.com/5hux1n/codexm'),
'app.footer': ('CopyRight @CodexM v%@  build by', 'CopyRight @CodexM v%@  build by'),
'action.stop': ('Stop', '停止'),
})
rows.update({
'native.openTarget': ('Open Target Account', '打开目标账户'),
'native.launchFailed': ('Import succeeded, but the target account could not be opened. Click Open Target Account to retry; no reimport is needed.', '任务已导入成功，但未能打开目标账户。点击“打开目标账户”重试即可，无需重新导入。'),
})
rows.update({'native.mode': ('Handoff method', '接力方式'), 'native.mode.native': ('Native History Import', '原生任务迁移'), 'native.mode.context': ('Context Handoff', '上下文接力'), 'native.intro': ('Copy the original task and its unredacted history, preserving its ID. The source stays unchanged. Account credentials are excluded. Import uses the official local history loader; continuing with another account still needs verification. Unsupported tasks can use Context Handoff.', '复制原任务及未经脱敏的完整历史，保留任务 ID，源任务保持不变；不复制登录凭据。由官方本地程序加载历史，跨账户继续执行仍需验证。不支持的任务可切换为上下文接力。'), 'native.paused': ('I have paused this task in the source account and will not run it in both accounts.', '我已暂停源账户中的此任务，不会在两个账户同时继续执行。'), 'native.import': ('Import and Open Target', '导入并打开目标账户'), 'native.targetRunning': ('Stop the target account before importing.', '导入前需要停止目标账户。'), 'native.stopTarget': ('Stop Target Account', '停止目标账户'), 'native.recent': ('Native imports and recovery', '原生迁移记录与恢复'), 'native.status.prepared': ('Prepared · target unchanged', '准备阶段 · 目标未改动'), 'native.status.importing': ('Interrupted import · recovery required', '导入中断 · 需要恢复'), 'native.status.verified': ('Local history imported and verified', '本地历史已导入并验证'), 'native.status.failed': ('Import failed · backup retained', '导入失败 · 已保留备份'), 'native.status.restoring': ('Interrupted recovery · backup retained', '恢复中断 · 已保留备份'), 'native.status.rolledBack': ('Rolled back', '已回滚'), 'native.threadID': ('Original task ID: %@', '原任务 ID：%@'), 'native.evidence': ('%d turns and %d history items verified across helper restart.', '已验证 %d 轮、%d 个历史条目，重启本地服务后内容一致。'), 'native.next': ('After import, the target account opens automatically. Find this task in its task list; no context pasting is needed. Check the history, then manually send a small continuation request. Import verification does not establish cross-account execution compatibility.', '导入成功后自动打开目标账户，在任务列表中找到这个原任务即可，无需复制或粘贴上下文。先检查历史，再手动发送一条简短的继续指令。导入验证不代表已证明跨账户执行兼容。'), 'native.recoveryHint': ('No successful native continuation is claimed. The backup and migration record are kept locally. Use rollback if available; interrupted operations require recovery before retrying.', '当前未确认原生续接成功。备份和迁移记录均保存在本机；可用时点击回滚，操作中断时请先恢复再重试。'), 'native.rollbackHint': ('A local backup protects the target’s existing task data if import fails. The source task remains unchanged. Rollback requires the target account to be stopped and its history to be unchanged since import. New target activity blocks rollback to protect new work. Credentials are never restored or overwritten.', '备份用于在导入失败时恢复目标账户原有的任务数据，源任务仍然保留。回滚要求目标账户已停止，且任务数据自导入后没有变化。目标产生新数据后会阻止回滚，避免丢失新工作；不会恢复或覆盖登录凭据。'), 'native.backup': ('Show Backup', '查看备份'), 'native.rollback': ('Roll Back Import', '回滚本次导入'), 'native.error.busy': ('The target account or its data is in use. Stop its Codex windows and try again.', '目标账户或其数据仍在使用中，请停止目标 Codex 后重试。'), 'native.error.conflict': ('The target already contains this task. It will not be overwritten.', '目标账户已存在此任务，不会覆盖。'), 'native.error.incompatible': ('This runtime or data format has not been verified for native import. Use Context Handoff.', '当前客户端版本或数据格式尚未验证原生导入兼容性，请使用上下文接力。'), 'native.error.unsupported': ('This first version supports unarchived standalone tasks only. Tasks with child tasks, goals, artifacts or dynamic tools need Context Handoff.', '第一版支持未归档的独立任务。关联子任务、目标、附件或动态工具的任务请使用上下文接力。'), 'native.error.changed': ('Task data changed during the operation. Pause the source task and stop the target before retrying.', '操作期间任务数据发生变化，请暂停源任务并停止目标账户后重试。'), 'native.error.invalid': ('Migration data, paths, checksums or available disk space failed validation. No credentials will be copied.', '迁移数据、路径、校验和或可用磁盘空间检查未通过，不会复制凭据。'), 'native.error.helper': ('The official local history loader did not complete verification. The migration record retains recovery information.', '官方本地历史加载未通过验证，迁移记录中保留了恢复信息。'), 'native.error.rollbackChanged': ('The target has changed since import. Rollback was blocked to preserve newer work. The original backup is retained.', '目标数据在导入后发生了变化，为保留后续工作已阻止回滚，原始备份仍然保留。'), 'native.error.recovery': ('This migration needs recovery before further imports. Keep the backup and avoid modifying the target.', '此迁移需要先恢复才能再次导入。请保留备份，暂勿修改目标数据。')})
rows.update({
'native.recover': ('Recover Interrupted Import', '恢复中断的导入'),
'native.recoverConfirm': ('Restore task data to the backup from before this import? All current task data will first be preserved in a separate recovery folder. Account credentials stay unchanged.', '将任务数据恢复到本次导入之前的备份？当前任务数据会先完整另存至恢复目录，登录凭据保持不变。'),
})
rows.update({
'native.error.runtime': ('Unable to identify the selected official local program. Locate the installed ChatGPT app in Settings.', '无法识别所选官方本地程序，请在设置中重新选择已安装的 ChatGPT。'),
'native.error.capability': ('The current official program could not reliably load this task in an isolated test. The target account has not been modified. Use Context Handoff for this task.', '当前官方程序未能在隔离试读中稳定重建此任务，目标账户尚未写入。此任务请使用上下文接力。'),
'native.error.incompatible': ('The task database or history format is not recognized. The check is based on structure and isolated loading, not an exact version-number match.', '任务数据库结构或历史格式无法识别。当前检查依据数据结构和隔离试读，不再要求版本号完全一致。'),
'native.stopTarget': ('Stop Only Target Account', '仅停止目标账户'),
})
rows.update({
'native.error.diagnostic': ('Native history processing failed at %@ (code: %@). No successful import is claimed. If this happened during compatibility checking, the target was not written.', '原生历史处理在“%@”阶段失败（代码：%@），未确认导入成功。若发生在兼容性试读阶段，目标账户尚未写入。'),
'native.stage.load': ('Isolated history loading', '隔离历史加载'),
'native.stage.initialize': ('Starting the official service', '启动官方服务'),
'native.stage.resume': ('Loading the original task', '加载原任务'),
'native.stage.read': ('Reading task metadata', '读取任务信息'),
'native.stage.page': ('Reading paginated history', '读取分页历史'),
'native.stage.restart': ('Reading history after restart', '重启后读取历史'),
'native.stage.compare': ('Comparing history across restart', '重启前后历史对比'),
'native.stage.rollout': ('Checking original history preservation', '原始历史完整性检查'),
'native.stage.schema': ('Checking reconstructed data structure', '重建数据结构检查'),
})
output = {"sourceLanguage": "en", "strings": {key: {"extractionState": "manual", "localizations": {lang: {"stringUnit": {"state": "translated", "value": value}} for lang, value in zip(['en','zh-Hans'], pair)}} for key, pair in sorted(rows.items())}, "version": "1.0"}
path = Path(__file__).resolve().parents[1] / 'CodexM/Resources/Localizable.xcstrings'
path.write_text(json.dumps(output, ensure_ascii=False, indent=2) + '\n')
print(f'{len(rows)} bilingual strings written')
